# syntax=docker/dockerfile:1
FROM debian:oldstable
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y ccache
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-multilib
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y debootstrap shellcheck
ENV PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
