# syntax=docker/dockerfile:1
FROM debian:oldoldstable
RUN echo "deb http://archive.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y ccache
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-multilib
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y shellcheck
ENV PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
