# syntax=docker/dockerfile:1
FROM debian:testing
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-multilib
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y debootstrap shellcheck
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y sudo
