= iamroot-shell(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: iamroot-shell Manual
:man source: iamroot 3

== NAME

iamroot-shell - run a shell ready to emulate the syscall chroot(2) for
unprivileged users.

== SYNOPSIS

*iamroot-shell* [OPTIONS] [--]    [SCRIPT_FILE  [ARGS...]]

*iamroot-shell* [OPTIONS] [--] -c COMMAND [NAME [ARGS...]]

*iamroot-shell* [OPTIONS] [--] -s [ARGS...]

== DESCRIPTION

Runs the _command_ process in an _iamroot_ environment ready to emulate the
*chroot(2)* syscall for unprivileged _users_.

When called without arguments, *iamroot-shell* defaults to running an
interactive shell.

Under the hood, *iamroot-shell* preloads a library which intercepts some
*libc(7)* functions to emulates *chroot(2)* in a pure unprivileged process.

For a more thorough description of *sh(1)*, *bash(1)*, *zsh(1)* or any other
shells, please refers to their manuals.

== OPTIONS

*POSIX Shell related options*

**-c**::
	Read commands from command-line.

**-i**::
	Set interactive.

**-s**::
	Read commands from standard-input.

*iamroot specific options*

**--chroot DIR**::
	Absolute path to the root directory to chroot in.

**--path PATH**::
	PATH to use in chroot.

**--ld-library-path PATH**::
	LD_LIBRARY_PATH to use in chroot.

**--exec FILE**::
	Absolute path to the iamroot exec script to use.

**--library LIB**::
	Absolute path to the iamroot library to use.

**--fatal**::
	Abort on error.

**--debug**::
	Turn on debug mode.

**--debug-fd FD**::
	Set debug fd.

**--debug-ignore REGEX**::
	Regular expression of functions to ignore in debug mode.
	Does not imply --debug.

**--exec-ignore REGEX**::
	Regular expression of executable path to ignore at execve().

**--path-resolution-ignore REGEX**::
	Regular expression of path to ignore for path resolution in chroot.

**--version**::
	Print version.

**--help**::
	Print usage.

== ENVIRONMENT VARIABLES

**SHELL**::
	The shell interpreter to use.

**IAMROOTLVL**::
	Incremented by one each time an instance of iamroot-shell is started.

**IAMROOT_ROOT**::
	Set absolute path to root directory to chroot in.
	Equivalent to --chroot DIR.

**IAMROOT_PATH**::
	Set PATH to use in chroot.
	Equivalent to --path PATH.

**IAMROOT_LD_LIBRARY_PATH**::
	Set LD_LIBRARY_PATH to use in chroot.
	Equivalent to --ld-library-path PATH.

**IAMROOT_EXEC**::
	Set absolute path to exec script to use.
	Equivalent to --exec EXEC.

**IAMROOT_LIB_LINUX_2**::
	Set absolute path to library to use with loader ld-linux.so.2

**IAMROOT_LIB_LINUX_X86_64_2**::
	Set absolute path to library to use with loader ld-linux-x86-64.so.2

**IAMROOT_LIB_MUSL_X86_64_1**::
	Set absolute path to library to use with loader ld-musl-x86_64.so.1

**IAMROOT_LIB_LINUX_ARMHF_3**::
	Set absolute path to library to use with loader ld-linux-armhf.so.3

**IAMROOT_LIB_LINUX_AARCH64_1**::
	Set absolute path to library to use with loader ld-linux-aarch64.so.1

**IAMROOT_LIB_MUSL_AARCH64_1**::
	Set absolute path to library to use with loader ld-musl-aarch64.so.1

**IAMROOT_LIB**::
	Set absolute path to library to use.
	Equivalent to --library LIB.

**IAMROOT_FATAL**::
	Set abort on error.
	Equivalent to --fatal.

**IAMROOT_DEBUG**::
	Set debug mode.
	Equivalent to --debug.

**IAMROOT_DEBUG_FD**::
	Set debug fd.
	Equivalent to --debug-fd.

**IAMROOT_DEBUG_IGNORE**::
	Set functions to ignore in debug mode.
	Equivalent to --debug-ignore.

**IAMROOT_EXEC_IGNORE**::
	Set executable path to ignore in execve().
	Equivalent to --exec-ignore.

**IAMROOT_PATH_RESOLUTION_IGNORE**::
	Set path to ignore for path resolution in chroot.
	Equivalent to --path-resolution-ignore.

== EXAMPLES

Run an _interactive shell_ in an _iamroot_ environment

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# 

Print _effective_ user name

	[root@archlinux ~]# whoami
	root

Change root directory via *chroot(1)*

	[gportay@archlinux ~]$ mkdir -p alpine-minirootfs
	[gportay@archlinux ~]$ wget http://dl-cdn.alpinelinux.org/alpine/v3.13/releases/x86_64/alpine-minirootfs-3.13.0-x86_64.tar.gz
	[gportay@archlinux ~]$ tar xf alpine-minirootfs-3.13.0-x86_64.tar.gz -C alpine-minirootfs
	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# chroot alpine-minirootfs /bin/ash
	/ # cat /etc/os-release
	NAME="Alpine Linux"
	ID=alpine
	VERSION_ID=3.13.0
	PRETTY_NAME="Alpine Linux v3.13"
	HOME_URL="https://alpinelinux.org/"
	BUG_REPORT_URL="https://bugs.alpinelinux.org/"
	/ # sh --help
	BusyBox v1.32.1 () multi-call binary.
	
	Usage: sh [-/+OPTIONS] [-/+o OPT]... [-c 'SCRIPT' [ARG0 [ARGS]] / FILE [ARGS] / -s [ARGS]]
	
	Unix shell interpreter
	/ # ls /proc/self/cwd -l
	lrwxrwxrwx    1 root     root             0 Mar 24 20:53 /proc/self/cwd -> /
        / # ls -l /proc/self/root
	lrwxrwxrwx    1 root     root             0 Mar 24 20:53 /proc/self/root -> /home/gportay/alpine-minirootfs

Create a new Arch Linux system installation from scratch via *pacstrap(8)*

	[gportay@archlinux ~]$ iamroot-shell -c "pacman-key --gpgdir rootfs/etc/pacman.d/gnupg --init"
	gpg: /home/gportay/rootfs/etc/pacman.d/gnupg/trustdb.gpg: trustdb created
	gpg: no ultimately trusted keys found
	gpg: starting migration from earlier GnuPG versions
	gpg: porting secret keys from '/home/gportay/rootfs/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
	gpg: migration succeeded
	==> Generating pacman master key. This may take some time.
	gpg: Generating pacman keyring master key...
	gpg: key 55B1411FB5D6DEE8 marked as ultimately trusted
	gpg: directory '/home/gportay/rootfs/etc/pacman.d/gnupg/openpgp-revocs.d' created
	gpg: revocation certificate stored as '/home/gportay/rootfs/etc/pacman.d/gnupg/openpgp-revocs.d/069893F3399C1E876C0479D255B1411FB5D6DEE8.rev'
	gpg: Done
	==> Updating trust database...
	gpg: marginals needed: 3  completes needed: 1  trust model: pgp
	gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
	[gportay@archlinux ~]$ iamroot-shell -c "pacman-key --gpgdir rootfs/etc/pacman.d/gnupg --populate archlinux" 
	==> Appending keys from archlinux.gpg...
	==> Locally signing trusted keys in keyring...
	  -> Locally signed 5 keys.
	==> Importing owner trust values...
	gpg: setting ownertrust to 4
	gpg: setting ownertrust to 4
	gpg: inserting ownertrust of 4
	gpg: setting ownertrust to 4
	gpg: setting ownertrust to 4
	==> Disabling revoked keys in keyring...
	  -> Disabled 49 keys.
	==> Updating trust database...
	gpg: marginals needed: 3  completes needed: 1  trust model: pgp
	gpg: depth: 0  valid:   1  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 1u
	gpg: depth: 1  valid:   5  signed:  94  trust: 0-, 0q, 0n, 5m, 0f, 0u
	gpg: depth: 2  valid:  87  signed:  33  trust: 87-, 0q, 0n, 0m, 0f, 0u
	gpg: next trustdb check due at 2022-05-06
	[gportay@archlinux ~]$ iamroot-shell -c "pacstrap rootfs" && echo done
	==> Creating install root at rootfs
	==> Installing packages to rootfs
	(...)
	:: Running post-transaction hooks...
	( 1/10) Creating system user accounts...
	( 2/10) Updating journal message catalog...
	( 3/10) Reloading system manager configuration...
	  Skipped: Running in chroot.
	( 4/10) Updating udev hardware database...
	( 5/10) Applying kernel sysctl settings...
	  Skipped: Running in chroot.
	( 6/10) Creating temporary files...
	fchownat() of /run/systemd/netif failed: Operation not permitted
	fchownat() of /run/systemd/netif/links failed: Operation not permitted
	fchownat() of /run/systemd/netif/leases failed: Operation not permitted
	fchownat() of /run/systemd/netif/lldp failed: Operation not permitted
	fchownat() of /dev/snd/seq failed: Operation not permitted
	fchownat() of /dev/snd/timer failed: Operation not permitted
	fchownat() of /dev/loop-control failed: Operation not permitted
	fchmod() of /dev/vhost-net failed: Operation not permitted
	fchownat() of /run/log/journal failed: Operation not permitted
	error: command failed to execute correctly
	( 7/10) Reloading device manager configuration...
	  Skipped: Running in chroot.
	( 8/10) Arming ConditionNeedsUpdate...
	( 9/10) Rebuilding certificate stores...
	(10/10) Reloading system bus configuration...
	  Skipped: Running in chroot.
	done

Note: Some post-transaction hooks failed due to lack of privileges.

Change root directory via *arch-chroot(8)*

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# arch-chroot rootfs
	==> WARNING: rootfs is not a mountpoint. This may have undesirable side effects.
	[root@archlinux /]# ls -l /proc/self/cwd
	lrwxrwxrwx 1 root root 0 Mar 24 21:14 /proc/self/cwd -> /
	[root@archlinux /]# ls -l /proc/self/root
	lrwxrwxrwx 1 root root 0 Mar 24 21:14 /proc/self/root -> /home/gportay/rootfs

Create a new Alpine Linux system installation from scratch via *alpine-make-rootfs*

	[gportay@archlinux ~]$ iamroot-shell -c "alpine-make-rootfs alpine-rootfs --mirror-uri http://nl.alpinelinux.org/alpine --branch latest-stable" && echo done
	
	> Installing system
	fetch http://nl.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
	fetch http://nl.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
	(1/6) Installing musl (1.2.2-r7)
	(2/6) Installing busybox (1.34.1-r3)
	Executing busybox-1.34.1-r3.post-install
	(3/6) Installing alpine-baselayout (3.2.0-r18)
	Executing alpine-baselayout-3.2.0-r18.pre-install
	Executing alpine-baselayout-3.2.0-r18.post-install
	(4/6) Installing busybox-suid (1.34.1-r3)
	(5/6) Installing scanelf (1.3.3-r0)
	(6/6) Installing musl-utils (1.2.2-r7)
	Executing busybox-1.34.1-r3.trigger
	OK: 2 MiB in 6 packages
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	
	> Cleaning-up rootfs
	done

Change root directory via *chroot(8)*

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# ls -l /proc/self/cwd
	lrwxrwxrwx 1 root root 0 Dec 31 14:24 /proc/self/cwd -> /home/gportay
	[root@archlinux ~]# ls -l /proc/self/root
	lrwxrwxrwx 1 root root 0 Dec 31 14:24 /proc/self/root -> /
	[root@archlinux ~]# chroot alpine-rootfs /bin/sh
	/ # ls -l /proc/self/cwd
	lrwxrwxrwx    1 root     root             0 Dec 31 14:24 /proc/self/cwd -> /
	/ # ls -l /proc/self/root
	lrwxrwxrwx    1 root     root             0 Dec 31 14:24 /proc/self/root -> /home/gportay/alpine-rootfs

== BUGS

Report bugs at *https://github.com/gportay/iamroot/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright (c) 2021-2022 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

*iamroot(7)*, *sh(1)*, *chroot(2)*
