#!/bin/bash
#
# Copyright 2020-2022 Gaël PORTAY
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#

VERSION=3

usage() {
	cat <<EOF
Usage: ${0##*/} [OPTIONS] [--]    [SCRIPT_FILE  [ARGS...]]
       ${0##*/} [OPTIONS] [--] -c COMMAND [NAME [ARGS...]]
       ${0##*/} [OPTIONS] [--] -s [ARGS...]

Runs the command process in an iamroot environment ready to emulate the
chroot(2) syscall for unprivileged users.

For a more thorough description of sh(1), bash(1), zsh(1) or any other shells,
please refers to their manuals.

POSIX Shell related options:

      -c                        Read commands from command-line.
      -i                        Set interactive.
      -s                        Read commands from standard-input.

iamroot specific options:
      --chroot DIR              Absolute path to the root directory to chroot
                                in.
      --path PATH               PATH to use in chroot.
      --ld-library-path PATH    LD_LIBRARY_PATH to use in chroot.
      --exec FILE               Absolute path to the iamroot exec script to
                                use.
      --library LIB             Absolute path to the iamroot library to use.
      --fatal                   Abort on error.
      --debug                   Turn on debug mode.
      --debug-fd FD             Set debug fd.
      --debug-ignore REGEX      Regular expression of functions to ignore in
                                debug mode.
                                Does not imply --debug.
      --exec-ignore REGEX       Regular expression of executable path to ignore
                                at execve().
      --path-resolution-ignore REGEX
                                Regular expression of path to ignore for path
                                resolution in chroot.
      --version                 Print version.
      --help                    Print usage.

Environment variables:
      SHELL                     The shell interpreter to use.

      IAMROOTLVL                Incremented by one each time an instance of
                                iamroot-shell is started.

      IAMROOT_ROOT              Set absolute path to root directory to chroot
                                in. Equivalent to --chroot DIR.

      IAMROOT_PATH              Set PATH to use in chroot.
                                Equivalent to --path PATH.

      IAMROOT_LD_LIBRARY_PATH   Set LD_LIBRARY_PATH to use in chroot.
                                Equivalent to --ld-library-path PATH.

      IAMROOT_EXEC              Set absolute path to exec script to use.
                                Equivalent to --exec EXEC.

      IAMROOT_LIB               Set absolute path to library to use.
                                Equivalent to --library LIB.

      IAMROOT_LIB_LINUX_2
                                Set absolute path to library to use with loader
                                ld-linux.so.2

      IAMROOT_LIB_LINUX_X86_64_2
                                Set absolute path to library to use with loader
                                ld-linux-x86-64.so.2

      IAMROOT_LIB_MUSL_X86_64_1 Set absolute path to library to use with loader
                                ld-musl-x86_64.so.1

      IAMROOT_LIB_LINUX_ARMHF_3
                                Set absolute path to library to use with loader
                                ld-linux-armhf.so.3

      IAMROOT_LIB_LINUX_AARCH64_1
                                Set absolute path to library to use with loader
                                ld-linux-aarch64.so.1

      IAMROOT_LIB_MUSL_AARCH64_1
                                Set absolute path to library to use with loader
                                ld-musl-aarch64.so.1

      IAMROOT_FATAL             Set abort on error.
                                Equivalent to --fatal.

      IAMROOT_DEBUG             Set debug mode.
                                Equivalent to --debug.

      IAMROOT_DEBUG_FD          Set debug fd.
                                Equivalent to --debug-fd.

      IAMROOT_DEBUG_IGNORE      Set functions to ignore in debug mode.
                                Equivalent to --debug-ignore.

      IAMROOT_EXEC_IGNORE       Set executable path to ignore in execve().
                                Equivalent to --exec-ignore.

      IAMROOT_PATH_RESOLUTION_IGNORE
                                Set path to ignore for path resolution in
                                chroot.
                                Equivalent to --path-resolution-ignore.
EOF
}

IAMROOT_LIB="${IAMROOT_LIB:-$PWD/x86_64/libiamroot-linux-x86-64.so.2}"
export IAMROOT_LIB

IAMROOT_LIB_LINUX_2="${IAMROOT_LIB_LINUX:-$PWD/i686/libiamroot-linux.so.2}"
export IAMROOT_LIB_LINUX_2

IAMROOT_LIB_LINUX_X86_64_2="${IAMROOT_LIB_LINUX_X86_64:-$PWD/x86_64/libiamroot-linux-x86-64.so.2}"
export IAMROOT_LIB_LINUX_X86_64_2

IAMROOT_LIB_LINUX_3="${IAMROOT_LIB_LINUX:-$PWD/arm/libiamroot-linux.so.3}"
export IAMROOT_LIB_LINUX_3

IAMROOT_LIB_LINUX_ARMHF_3="${IAMROOT_LIB_LINUX_ARMHF:-$PWD/armhf/libiamroot-linux-armhf.so.3}"
export IAMROOT_LIB_LINUX_ARMHF_3

IAMROOT_LIB_LINUX_AARCH64_1="${IAMROOT_LIB_LINUX_AARCH64:-$PWD/aarch64/libiamroot-linux-aarch64.so.1}"
export IAMROOT_LIB_LINUX_AARCH64_1

IAMROOT_LIB_MUSL_X86_64_1="${IAMROOT_LIB_MUSL_X86_64:-$PWD/x86_64/libiamroot-musl-x86_64.so.1}"
export IAMROOT_LIB_MUSL_X86_64_1

IAMROOT_LIB_MUSL_AARCH64_1="${IAMROOT_LIB_MUSL_AARCH64:-$PWD/aarch64/libiamroot-musl-aarch64.so.1}"
export IAMROOT_LIB_MUSL_AARCH64_1

IAMROOT_EXEC="${IAMROOT_EXEC:-$PWD/exec.sh}"
export IAMROOT_EXEC

argv=()
while [[ "$#" -ne 0 ]]
do
	if [[ "$1" == "--help" ]]
	then
		usage
		exit 0
	elif [[ "$1" == "--version" ]]
	then
		echo "$VERSION"
		exit 0
	elif [[ "$1" == "--path-resolution-ignore" ]]
	then
		shift
		IAMROOT_PATH_RESOLUTION_IGNORE="$1"
		export IAMROOT_PATH_RESOLUTION_IGNORE
	elif [[ "$1" == "--exec-ignore" ]]
	then
		shift
		IAMROOT_EXEC_IGNORE="$1"
		export IAMROOT_EXEC_IGNORE
	elif [[ "$1" == "--debug-ignore" ]]
	then
		shift
		IAMROOT_DEBUG_IGNORE="$1"
		export IAMROOT_DEBUG_IGNORE
	elif [[ "$1" == "--debug-fd" ]]
	then
		shift
		IAMROOT_DEBUG_FD="$1"
		export IAMROOT_DEBUG_FD
	elif [[ "$1" == "--debug" ]]
	then
		IAMROOT_DEBUG="$((IAMROOT_DEBUG+1))"
		export IAMROOT_DEBUG
	elif [[ "$1" == "--fatal" ]]
	then
		IAMROOT_FATAL="1"
		export IAMROOT_FATAL
	elif [[ "$1" == "--library" ]]
	then
		shift
		IAMROOT_LIB="$1"
		export IAMROOT_LIB
	elif [[ "$1" == "--exec" ]]
	then
		shift
		IAMROOT_EXEC="$1"
		export IAMROOT_EXEC
	elif [[ "$1" == "--chroot" ]]
	then
		shift
		IAMROOT_ROOT="$1"
		export IAMROOT_ROOT
	elif [[ "$1" == "--path" ]]
	then
		shift
		IAMROOT_PATH="$1"
		export IAMROOT_PATH
	elif [[ "$1" == "--ld-library-path" ]]
	then
		shift
		IAMROOT_LD_LIBRARY_PATH="$1"
		export IAMROOT_LD_LIBRARY_PATH
	elif [[ "$1" == "--" ]]
	then
		shift
		break
	else
		break
	fi
	shift
done

if [[ "${IAMROOT_DEBUG_FD:-}" ]] && [[ ! -e "/proc/$$/$IAMROOT_DEBUG_FD" ]]
then
	exec {IAMROOT_DEBUG_FD}>&2
fi

EUID=0 \
IAMROOTLVL="$((IAMROOTLVL+1))" \
LD_PRELOAD="$IAMROOT_LIB${LD_PRELOAD+:$LD_PRELOAD}" \
exec "${SHELL:-/bin/sh}" "${argv[@]}" "$@"
