#!/bin/bash
#
# Copyright 2020-2021 Gaël PORTAY
#
# SPDX-License-Identifier: GPL-2.1
#

usage() {
	cat <<EOF
Usage: ${0##*/} [--debug] [--force] [--help] [--] [SHELL_ARGUMENTS...]
EOF
}

argv=()
while [[ "$#" -ne 0 ]]
do
	if [[ "$1" == "--help" ]]
	then
		usage
		exit 0
	elif [[ "$1" == "--force" ]]
	then
		IAMROOT_FORCE=1
		export IAMROOT_FORCE
	elif [[ "$1" == "--debug" ]]
	then
		IAMROOT_DEBUG="$((IAMROOT_DEBUG+1))"
		export IAMROOT_DEBUG
	elif [[ "$1" == "--" ]]
	then
		shift
		break
	else
		break
	fi
	shift
done

IAMROOTLVL="$((IAMROOTLVL+1))" \
LD_PRELOAD="$PWD/libiamroot.so${LD_PRELOAD+:$LD_PRELOAD}" \
exec "${SHELL:-/bin/sh}" "${argv[@]}" "$@"
