= iamroot-shell(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: iamroot-shell Manual
:man source: iamroot 6

== NAME

iamroot-shell - run a shell ready to emulate the syscall chroot(2) for
unprivileged users.

== SYNOPSIS

*iamroot-shell* [OPTIONS] [--]    [SCRIPT_FILE  [ARGS...]]

*iamroot-shell* [OPTIONS] [--] -c COMMAND [NAME [ARGS...]]

*iamroot-shell* [OPTIONS] [--] -s [ARGS...]

== DESCRIPTION

Runs the _command_ process in an _iamroot_ environment ready to emulate the
*chroot(2)* syscall for unprivileged _users_.

When called without arguments, *iamroot-shell* defaults to running an
interactive shell.

Under the hood, *iamroot-shell* preloads a library which intercepts some
*libc(7)* functions to emulates *chroot(2)* in a pure unprivileged process.

For a more thorough description of *sh(1)*, *bash(1)*, *zsh(1)* or any other
shells, please refers to their manuals.

== OPTIONS

*POSIX Shell related options*

**-c**::
	Read commands from command-line.

**-i**::
	Set interactive.

**-s**::
	Read commands from standard-input.

*iamroot specific options*

**--chroot DIR**::
	Absolute path to the root directory to chroot in.

**--profile-file FILE**::
	Execute initialization file from FILE.

**--rc-file FILE**::
	Execute commands from FILE.

**--path PATH**::
	PATH to use in chroot.

**--library-path PATH**::
	LD_LIBRARY_PATH to use in chroot.

**--exec FILE**::
	Absolute path to the iamroot exec script to use.

**--library LIB**::
	Absolute path to the iamroot library to use.

**--fatal**::
	Abort on error.

**--no-color**::
	Turn off color.

**--debug**::
	Turn on debug mode.

**--debug-fd FD**::
	Set debug fd.

**--debug-allow REGEX**::
	Regular expression of functions to allow in debug mode.
	Does not imply --debug.

**--debug-ignore REGEX**::
	Regular expression of functions to ignore in debug mode.
	Does not imply --debug.

**--exec-ignore REGEX**::
	Regular expression of executable path to ignore at execve().

**--path-resolution-allow REGEX**::
	Regular expression of path to allow for path resolution in chroot.

**--path-resolution-ignore REGEX**::
	Regular expression of path to ignore for path resolution in chroot.

**--version**::
	Print version.

**--help**::
	Print usage.

== ENVIRONMENT VARIABLES

**SHELL**::
	The shell interpreter to use.

**IAMROOTLVL**::
	Incremented by one each time an instance of iamroot-shell is started.

**IAMROOT_ROOT**::
	Set absolute path to root directory to chroot in.
	Equivalent to --chroot DIR.

**IAMROOT_PROFILE_FILE**::
	Set path to initialization file.
	Equivalent to --profile-file FILE.

**IAMROOT_RC_FILE**::
	Set path to command file.
	Equivalent to --rc-file FILE.

**IAMROOT_PATH**::
	Set PATH to use in chroot.
	Equivalent to --path PATH.

**IAMROOT_LIBRARY_PATH**::
	Set LD_LIBRARY_PATH to use in chroot.
	Equivalent to --library-path PATH.

**IAMROOT_EXEC**::
	Set absolute path to exec script to use.
	Equivalent to --exec EXEC.

**IAMROOT_LIB**::
	Set absolute path to library to use.
	Equivalent to --library LIB.

**IAMROOT_FATAL**::
	Set abort on error.
	Equivalent to --fatal.

**IAMROOT_DEBUG**::
	Turn on debug mode.
	Equivalent to --debug.

**IAMROOT_DEBUG_FD**::
	Set debug fd.
	Equivalent to --debug-fd.

**IAMROOT_DEBUG_ALLOW**::
	Set functions to allow in debug mode.
	Equivalent to --debug-allow.

**IAMROOT_DEBUG_IGNORE**::
	Set functions to ignore in debug mode.
	Equivalent to --debug-ignore.

**IAMROOT_EXEC_IGNORE**::
	Set executable path to ignore in execve().
	Equivalent to --exec-ignore.

**IAMROOT_PATH_RESOLUTION_ALLOW**::
	Set path to allow for path resolution in chroot.
	Equivalent to --path-resolution-allow.

**IAMROOT_PATH_RESOLUTION_IGNORE**::
	Set path to ignore for path resolution in chroot.
	Equivalent to --path-resolution-ignore.

== EXAMPLES

Run an _interactive shell_ in an _iamroot_ environment

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# 

Print _effective_ user name

	[root@archlinux ~]# whoami
	root

Change root directory via *chroot(1)*

	[gportay@archlinux ~]$ mkdir -p alpine-minirootfs
	[gportay@archlinux ~]$ wget http://dl-cdn.alpinelinux.org/alpine/v3.13/releases/x86_64/alpine-minirootfs-3.13.0-x86_64.tar.gz
	[gportay@archlinux ~]$ tar xf alpine-minirootfs-3.13.0-x86_64.tar.gz -C alpine-minirootfs
	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# chroot alpine-minirootfs /bin/ash
	/ # cat /etc/os-release
	NAME="Alpine Linux"
	ID=alpine
	VERSION_ID=3.13.0
	PRETTY_NAME="Alpine Linux v3.13"
	HOME_URL="https://alpinelinux.org/"
	BUG_REPORT_URL="https://bugs.alpinelinux.org/"
	/ # sh --help
	BusyBox v1.32.1 () multi-call binary.
	
	Usage: sh [-/+OPTIONS] [-/+o OPT]... [-c 'SCRIPT' [ARG0 [ARGS]] / FILE [ARGS] / -s [ARGS]]
	
	Unix shell interpreter
	/ # ls /proc/self/cwd -l
	lrwxrwxrwx    1 root     root             0 Mar 24 20:53 /proc/self/cwd -> /
        / # ls -l /proc/self/root
	lrwxrwxrwx    1 root     root             0 Mar 24 20:53 /proc/self/root -> /home/gportay/alpine-minirootfs

Create a new Arch Linux system installation from scratch via *pacstrap(8)*

	[gportay@archlinux ~]$ EUID=0 iamroot-shell -c "pacman-key --gpgdir rootfs/etc/pacman.d/gnupg --init"
	gpg: /home/gportay/rootfs/etc/pacman.d/gnupg/trustdb.gpg: trustdb created
	gpg: no ultimately trusted keys found
	gpg: starting migration from earlier GnuPG versions
	gpg: porting secret keys from '/home/gportay/rootfs/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
	gpg: migration succeeded
	==> Generating pacman master key. This may take some time.
	gpg: Generating pacman keyring master key...
	gpg: key 63E3BF33B8A41C04 marked as ultimately trusted
	gpg: directory '/home/gportay/rootfs/etc/pacman.d/gnupg/openpgp-revocs.d' created
	gpg: revocation certificate stored as '/home/gportay/rootfs/etc/pacman.d/gnupg/openpgp-revocs.d/772F83A308F9F12BC32A1D8A63E3BF33B8A41C04.rev'
	gpg: Done
	==> Updating trust database...
	gpg: marginals needed: 3  completes needed: 1  trust model: pgp
	gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
	[gportay@archlinux ~]$ EUID=0 iamroot-shell -c "pacman-key --gpgdir rootfs/etc/pacman.d/gnupg --populate archlinux"
	==> Appending keys from archlinux.gpg...
	==> Locally signing trusted keys in keyring...
	  -> Locally signed 6 keys.
	==> Importing owner trust values...
	gpg: setting ownertrust to 4
	gpg: setting ownertrust to 4
	gpg: setting ownertrust to 4
	gpg: inserting ownertrust of 4
	gpg: setting ownertrust to 4
	gpg: setting ownertrust to 4
	==> Disabling revoked keys in keyring...
	  -> Disabled 49 keys.
	==> Updating trust database...
	gpg: marginals needed: 3  completes needed: 1  trust model: pgp
	gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
	gpg: depth: 1  valid:   6  signed:  94  trust: 0-, 0q, 0n, 6m, 0f, 0u
	gpg: depth: 2  valid:  88  signed:  32  trust: 88-, 0q, 0n, 0m, 0f, 0u
	gpg: next trustdb check due at 2022-05-06
	[gportay@archlinux ~]$ EUID=0 iamroot-shell -c "pacstrap rootfs" && echo done
	==> Creating install root at rootfs
	Warning: Command is skipped: /usr/bin/mount proc rootfs/proc -t proc -o nosuid,noexec,nodev
	Warning: Command is skipped: /usr/bin/mount sys rootfs/sys -t sysfs -o nosuid,noexec,nodev,ro
	Warning: Command is skipped: /usr/bin/mount udev rootfs/dev -t devtmpfs -o mode=0755,nosuid
	Warning: Command is skipped: /usr/bin/mount devpts rootfs/dev/pts -t devpts -o mode=0620,gid=5,nosuid,noexec
	Warning: Command is skipped: /usr/bin/mount shm rootfs/dev/shm -t tmpfs -o mode=1777,nosuid,nodev
	Warning: Command is skipped: /usr/bin/mount /run rootfs/run --bind
	Warning: Command is skipped: /usr/bin/mount tmp rootfs/tmp -t tmpfs -o mode=1777,strictatime,nodev,nosuid
	==> Installing packages to rootfs
	(...)
	:: Running post-transaction hooks...
	( 1/10) Creating system user accounts...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	( 2/10) Updating journal message catalog...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	( 3/10) Reloading system manager configuration...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	  Skipped: Running in chroot.
	( 4/10) Updating udev hardware database...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	( 5/10) Applying kernel sysctl settings...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	  Skipped: Running in chroot.
	( 6/10) Creating temporary files...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	Warning: fchownat: /run/tpm2-tss/eventlog: Ignoring error 'Operation not permitted'!
	Warning: chmod: /run/tpm2-tss/eventlog: Ignoring error 'Operation not permitted'!
	Warning: fchownat: /dev/snd/seq: Ignoring error 'Operation not permitted'!
	Warning: chmod: /dev/snd/seq: Ignoring error 'Operation not permitted'!
	Warning: fchownat: /dev/snd/timer: Ignoring error 'Operation not permitted'!
	Warning: chmod: /dev/snd/timer: Ignoring error 'Operation not permitted'!
	Warning: fchownat: /dev/loop-control: Ignoring error 'Operation not permitted'!
	Warning: chmod: /dev/loop-control: Ignoring error 'Operation not permitted'!
	Warning: chmod: /dev/vhost-net: Ignoring error 'Operation not permitted'!
	Warning: fchownat: /run/log/journal: Ignoring error 'Operation not permitted'!
	Warning: chmod: /run/log/journal: Ignoring error 'Operation not permitted'!
	( 7/10) Reloading device manager configuration...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	  Skipped: Running in chroot.
	( 8/10) Arming ConditionNeedsUpdate...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	( 9/10) Rebuilding certificate stores...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	(10/10) Reloading system bus configuration...
	Warning: /home/gportay/rootfs: contains root '/home/gportay/rootfs'
	  Skipped: Running in chroot.
	Warning: Command is skipped: /usr/bin/umount rootfs/tmp rootfs/run rootfs/dev/shm rootfs/dev/pts rootfs/dev rootfs/sys rootfs/proc
	done

Note: Some post-transaction hooks failed due to lack of privileges.

Change root directory via *arch-chroot(8)*

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# arch-chroot rootfs
	==> ERROR: This script must be run with root privileges
	[root@archlinux ~]# ls -l /proc/self/cwd
	lrwxrwxrwx 1 root root 0 Apr 25 09:57 /proc/self/cwd -> /home/gportay
	[root@archlinux ~]# ls -l /proc/self/root
	lrwxrwxrwx 1 root root 0 Apr 25 09:57 /proc/self/root -> /

Create a new Alpine Linux system installation from scratch via *alpine-make-rootfs*

	[gportay@archlinux ~]$ iamroot-shell -c "alpine-make-rootfs alpine-rootfs --keys-dir /usr/share/apk/keys/x86_64 --mirror-uri http://nl.alpinelinux.org/alpine" && echo done
	
	> Installing system
	fetch http://nl.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
	fetch http://nl.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
	(1/6) Installing musl (1.2.2-r7)
	(2/6) Installing busybox (1.34.1-r5)
	Executing busybox-1.34.1-r5.post-install
	(3/6) Installing alpine-baselayout (3.2.0-r18)
	Executing alpine-baselayout-3.2.0-r18.pre-install
	Executing alpine-baselayout-3.2.0-r18.post-install
	(4/6) Installing busybox-suid (1.34.1-r5)
	(5/6) Installing scanelf (1.3.3-r0)
	(6/6) Installing musl-utils (1.2.2-r7)
	Executing busybox-1.34.1-r5.trigger
	OK: 2 MiB in 6 packages
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	
	> Cleaning-up rootfs
	done

Change root directory via *chroot(8)*

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# ls -l /proc/self/cwd
	lrwxrwxrwx 1 root root 0 Apr 25 09:54 /proc/self/cwd -> /home/gportay
	[root@archlinux ~]# ls -l /proc/self/root
	lrwxrwxrwx 1 root root 0 Apr 25 09:54 /proc/self/root -> /
	[iamroot][root@archlinux ~]# chroot alpine-rootfs /bin/sh
	/ # ls -l /proc/self/cwd
	lrwxrwxrwx    1 root     root             0 Apr 25 09:54 /proc/self/cwd -> /
	/ # ls -l /proc/self/root
	lrwxrwxrwx    1 root     root             0 Apr 25 09:55 /proc/self/root -> /home/gportay/alpine-rootfs

== BUGS

Report bugs at *https://github.com/gportay/iamroot/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright (c) 2021-2022 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

*iamroot(7)*, *sh(1)*, *chroot(2)*
