= iamroot-shell(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: iamroot-shell Manual
:man source: iamroot 2

== NAME

iamroot-shell - run a shell ready to emulate the syscall chroot(2) for
unprivileged users.

== SYNOPSIS

*iamroot-shell* [OPTIONS] [--]    [SCRIPT_FILE  [ARGS...]]

*iamroot-shell* [OPTIONS] [--] -c COMMAND [NAME [ARGS...]]

*iamroot-shell* [OPTIONS] [--] -s [ARGS...]

== DESCRIPTION

Runs the _command_ process in an _iamroot_ environment ready to emulate the
*chroot(2)* syscall for unprivileged _users_.

When called without arguments, *iamroot-shell* defaults to running an
interactive shell.

Under the hood, *iamroot-shell* preloads a library which intercepts some
*libc(7)* functions to emulates *chroot(2)* in a pure unprivileged process.

For a more thorough description of *sh(1)*, *bash(1)*, *zsh(1)* or any other
shells, please refers to their manuals.

== OPTIONS

*POSIX Shell related options*

**-c**::
	Read commands from command-line.

**-i**::
	Set interactive.

**-s**::
	Read commands from standard-input.

*iamroot specific options*

**--chroot DIR**::
	Absolute path to the root directory to chroot in.

**--path PATH**::
	PATH to use in chroot.

**--ld-library-path PATH**::
	LD_LIBRARY_PATH to use in chroot.

**--exec FILE**::
	Absolute path to the iamroot exec script to use.

**--library LIB**::
	Absolute path to the iamroot library to use.

**--debug**::
	Turn on debug mode.

**--debug-ignore REGEX**::
	Regular expression of functions to ignore in debug mode.
	Does not imply --debug.

**--version**::
	Print version.

**--help**::
	Print usage.

== ENVIRONMENT VARIABLES

**SHELL**::
	The shell interpreter to use.

**IAMROOTLVL**::
	Incremented by one each time an instance of iamroot-shell is started.

**IAMROOT_ROOT**::
	Set absolute path to root directory to chroot in.
	Equivalent to --chroot DIR.

**IAMROOT_PATH**::
	Set PATH to use in chroot.
	Equivalent to --path PATH.

**IAMROOT_LD_LIBRARY_PATH**::
	Set LD_LIBRARY_PATH to use in chroot.
	Equivalent to --ld-library-path PATH.

**IAMROOT_EXEC**::
	Set absolute path to exec script to use.
	Equivalent to --exec EXEC.

**IAMROOT_LIB**::
	Set absolute path to library to use.
	Equivalent to --library LIB.

**IAMROOT_DEBUG**::
	Set debug mode.
	Equivalent to --debug.

**IAMROOT_DEBUG_IGNORE**::
	Set functions to ignore in debug mode. 
	Equivalent to --debug-ignore.

**IAMROOT_EXEC_IGNORE**::
	Set executable path to ignore in execve().
	Equivalent to --exec-ignore.

**IAMROOT_PATH_RESOLUTION_IGNORE**::
	Set path to ignore for path resolution in chroot.
	Equivalent to --path-resolution-ignore.

== EXAMPLES

Run an _interactive shell_ in an _iamroot_ environment

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# 

Print _effective_ user name

	[root@archlinux ~]# whoami
	root

Change root directory via *chroot(1)*

	[gportay@archlinux ~]$ mkdir -p alpine-minirootfs
	[gportay@archlinux ~]$ wget http://dl-cdn.alpinelinux.org/alpine/v3.13/releases/x86_64/alpine-minirootfs-3.13.0-x86_64.tar.gz
	[gportay@archlinux ~]$ tar xf alpine-minirootfs-3.13.0-x86_64.tar.gz -C alpine-minirootfs
	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# chroot alpine-minirootfs /bin/ash
	/ # cat /etc/os-release
	NAME="Alpine Linux"
	ID=alpine
	VERSION_ID=3.13.0
	PRETTY_NAME="Alpine Linux v3.13"
	HOME_URL="https://alpinelinux.org/"
	BUG_REPORT_URL="https://bugs.alpinelinux.org/"
	/ # sh --help
	BusyBox v1.32.1 () multi-call binary.
	
	Usage: sh [-/+OPTIONS] [-/+o OPT]... [-c 'SCRIPT' [ARG0 [ARGS]] / FILE [ARGS] / -s [ARGS]]
	
	Unix shell interpreter
	/ # ls /proc/self/cwd -l
	lrwxrwxrwx    1 root     root             0 Mar 24 20:53 /proc/self/cwd -> /
        / # ls -l /proc/self/root
	lrwxrwxrwx    1 root     root             0 Mar 24 20:53 /proc/self/root -> /home/gportay/alpine-minirootfs

Create a new Arch Linux system installation from scratch via *pacstrap(8)*

	[gportay@archlinux ~]$ mkdir rootfs
	[gportay@archlinux ~]$ iamroot-shell -c "pacstrap rootfs" && echo done
	==> Creating install root at rootfs
	cp: cannot access '/etc/pacman.d/gnupg/crls.d': Permission denied
	cp: cannot access '/etc/pacman.d/gnupg/openpgp-revocs.d': Permission denied
	cp: cannot access '/etc/pacman.d/gnupg/private-keys-v1.d': Permission denied
	cp: cannot open '/etc/pacman.d/gnupg/secring.gpg' for reading: Permission denied
	==> Installing packages to rootfs
	(...)
	:: Running post-transaction hooks...
	( 1/10) Creating system user accounts...
	( 2/10) Updating journal message catalog...
	( 3/10) Reloading system manager configuration...
	  Skipped: Running in chroot.
	( 4/10) Updating udev hardware database...
	( 5/10) Applying kernel sysctl settings...
	  Skipped: Running in chroot.
	( 6/10) Creating temporary files...
	fchownat() of /run/systemd/netif failed: Operation not permitted
	Failed to create directory or subvolume "/run/systemd/netif/links": Permission denied
	Failed to create directory or subvolume "/run/systemd/netif/leases": Permission denied
	Failed to create directory or subvolume "/run/systemd/netif/lldp": Permission denied
	fchmod() of /dev/snd/seq failed: Operation not permitted
	fchmod() of /dev/snd/timer failed: Operation not permitted
	fchownat() of /dev/loop-control failed: Operation not permitted
	fchmod() of /dev/net/tun failed: Operation not permitted
	Setting access ACL "u::rwx,g::r-x,g:wheel:r-x,g:adm:r-x,m::r-x,o::r-x" on /run/log/journal failed: Operation not permitted
	fchownat() of /run/log/journal failed: Operation not permitted
	error: command failed to execute correctly
	( 7/10) Reloading device manager configuration...
	  Skipped: Running in chroot.
	( 8/10) Arming ConditionNeedsUpdate...
	( 9/10) Rebuilding certificate stores...
	(10/10) Reloading system bus configuration...
	  Skipped: Running in chroot.
	done

Note: Some post-transaction hooks failed due to lack of privileges.

Change root directory via *arch-chroot(8)*

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# arch-chroot rootfs
	==> WARNING: rootfs is not a mountpoint. This may have undesirable side effects.
	[root@archlinux /]# ls -l /proc/self/cwd
	lrwxrwxrwx 1 root root 0 Mar 24 21:14 /proc/self/cwd -> /
	[root@archlinux /]# ls -l /proc/self/root
	lrwxrwxrwx 1 root root 0 Mar 24 21:14 /proc/self/root -> /home/gportay/rootfs

Create a new Alpine Linux system installation from scratch via *alpine-make-rootfs*

	[gportay@archlinux ~]$ iamroot-shell -c "alpine-make-rootfs alpine-rootfs --mirror-uri http://nl.alpinelinux.org/alpine --branch latest-stable" && echo done
	
	> Installing system
	fetch http://nl.alpinelinux.org/alpine/latest-stable/main/x86_64/APKINDEX.tar.gz
	fetch http://nl.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
	(1/6) Installing musl (1.2.2-r3)
	(2/6) Installing busybox (1.33.1-r3)
	Executing busybox-1.33.1-r3.post-install
	(3/6) Installing alpine-baselayout (3.2.0-r16)
	Executing alpine-baselayout-3.2.0-r16.pre-install
	Executing alpine-baselayout-3.2.0-r16.post-install
	chown: unknown user/group root:shadow
	(4/6) Installing busybox-suid (1.33.1-r3)
	(5/6) Installing scanelf (1.3.2-r0)
	(6/6) Installing musl-utils (1.2.2-r3)
	Executing busybox-1.33.1-r3.trigger
	OK: 2 MiB in 6 packages
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	
	> Cleaning-up rootfs
	done

Change root directory via *chroot(8)*

	[gportay@archlinux ~]$ iamroot-shell
	[root@archlinux ~]# chroot alpine-rootfs /bin/ash
	lrwxrwxrwx 1 root root 0 Mar 24 21:14 /proc/self/root -> /home/gportay/rootfs
	[root@archlinux iamroot-multi-arch]# chroot alpine-rootfs /bin/sh
	/ # ls -l /proc/self/cwd
	lrwxrwxrwx    1 root     root             0 Sep 20 12:35 /proc/self/cwd -> /
	/ # ls -l /proc/self/root
	lrwxrwxrwx    1 root     root             0 Sep 20 12:35 /proc/self/root -> /home/gportay/src/iamroot-multi-arch/alpine-rootfs

== BUGS

Report bugs at *https://github.com/gportay/iamroot/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright (c) 2021 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

*iamroot(7)*, *sh(1)*, *chroot(2)*
