#!/usr/bin/env bash
#
# Copyright 2020-2024 Gaël PORTAY
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#

set -e

VERSION=20

usage() {
	cat <<EOF
Usage: ${0##*/} [OPTIONS] [--]    [SCRIPT_FILE  [ARGS...]]
       ${0##*/} [OPTIONS] [--] -c COMMAND [NAME [ARGS...]]
       ${0##*/} [OPTIONS] [--] -s [ARGS...]

Runs the command process in an iamroot environment ready to emulate the
chroot(2) syscall for unprivileged users.

For a more thorough description of sh(1), bash(1), zsh(1) or any other shells,
please refers to their manuals.

POSIX Shell related options:
      -c                        Read commands from command-line.
      -i                        Set interactive.
      -s                        Read commands from standard-input.

iamroot specific options:
      --root DIR                Absolute path to the root directory to chroot
                                in.
      --profile-file FILE       Execute initialization file from FILE.
      --rc-file FILE            Execute commands from FILE.
      --multiarch               Use multiarch library path in chroot.
      --libdir                  Set /lib:/usr/lib as default library path in
                                chroot.
      --deflib PATH             Default library path to use in chroot.
      --exec FILE               Absolute path to the iamroot exec script to
                                use.
      --library LIB             Absolute path to the iamroot library to use.
      --shell SHELL             Set shell interpretor.
                                Equivalent to set ISH=<SHELL>.
      --no-color                Turn off color.
      --fatal                   Abort on error.
      --debug                   Turn on debug mode.
      --debug-fd FD             Set debug fd.
      --debug-ignore REGEX      Regular expression of functions to ignore in
                                debug mode.
                                Does not imply --debug.
      --exec-ignore REGEX       Regular expression of executable path to ignore
                                at execve().
      --path-resolution-ignore  REGEX
                                Regular expression of path to ignore for path
                                resolution in chroot.
      --version                 Print version.
      --help                    Print usage.

Environment variables:
      SHELL                     The shell interpreter to use.

      ISHLVL                    Incremented by one each time an instance of
                                ish is started.

      IAMROOT_ROOT              Set absolute path to root directory to chroot
                                in. Equivalent to --root DIR.

      ISH_PROFILE_FILE          Set path to initialization file.
                                Equivalent to --profile-file FILE.

      ISH_RC_FILE               Set path to command file.
                                Equivalent to --rc-file FILE.

      IAMROOT_MULTIARCH         Use multiarch default library path in chroot.
                                Equivalent to --multiarch.

      IAMROOT_DEFLIB            Set default library path to use in chroot.
                                Equivalent to --deflib PATH.

      IAMROOT_EXEC              Set absolute path to exec script to use.
                                Equivalent to --exec EXEC.

      IAMROOT_LIB               Set absolute path to library to use.
                                Equivalent to --library LIB.

      IAMROOT_FATAL             Set abort on error.
                                Equivalent to --fatal.

      IAMROOT_DEBUG             Turn on debug mode.
                                Equivalent to --debug.

      IAMROOT_DEBUG_FD          Set debug fd.
                                Equivalent to --debug-fd.

      IAMROOT_DEBUG_IGNORE      Set functions to ignore in debug mode.
                                Equivalent to --debug-ignore.

      IAMROOT_EXEC_IGNORE       Set executable path to ignore in execve().
                                Equivalent to --exec-ignore.

      IAMROOT_PATH_RESOLUTION_IGNORE
                                Set path to ignore for path resolution in
                                chroot.
                                Equivalent to --path-resolution-ignore.
EOF
}

IAMROOT_LIB="${IAMROOT_LIB:-/usr/local/lib/iamroot/libiamroot.so}"
export IAMROOT_LIB

IAMROOT_EXEC="${IAMROOT_EXEC:-/usr/local/lib/iamroot/exec.sh}"
export IAMROOT_EXEC

while [[ "$#" -ne 0 ]]
do
	if [[ "$1" == "--help" ]]
	then
		usage
		exit
	elif [[ "$1" == "--version" ]]
	then
		echo "$VERSION"
		exit
	elif [[ "$1" == "--path-resolution-ignore" ]]
	then
		shift
		IAMROOT_PATH_RESOLUTION_IGNORE="$1"
		export IAMROOT_PATH_RESOLUTION_IGNORE
	elif [[ "$1" == "--exec-ignore" ]]
	then
		shift
		IAMROOT_EXEC_IGNORE="$1"
		export IAMROOT_EXEC_IGNORE
	elif [[ "$1" == "--debug-ignore" ]]
	then
		shift
		IAMROOT_DEBUG_IGNORE="$1"
		export IAMROOT_DEBUG_IGNORE
	elif [[ "$1" == "--debug-fd" ]]
	then
		shift
		IAMROOT_DEBUG_FD="$1"
		export IAMROOT_DEBUG_FD
	elif [[ "$1" == "--debug" ]]
	then
		IAMROOT_DEBUG="$((IAMROOT_DEBUG+1))"
		export IAMROOT_DEBUG
	elif [[ "$1" == "--fatal" ]]
	then
		IAMROOT_FATAL="1"
		export IAMROOT_FATAL
	elif [[ "$1" == "--no-color" ]]
	then
		NO_COLOR=1
		export NO_COLOR
	elif [[ "$1" == "--shell" ]]
	then
		shift
		SHELL="$1"
		export SHELL
	elif [[ "$1" == "--library" ]]
	then
		shift
		IAMROOT_LIB="$1"
		export IAMROOT_LIB
	elif [[ "$1" == "--exec" ]]
	then
		shift
		IAMROOT_EXEC="$1"
		export IAMROOT_EXEC
	elif [[ "$1" == "--deflib" ]]
	then
		shift
		IAMROOT_DEFLIB="$1"
		export IAMROOT_DEFLIB
	elif [[ "$1" == "--libdir" ]]
	then
		IAMROOT_DEFLIB="/lib:/usr/lib"
		export IAMROOT_DEFLIB
	elif [[ "$1" == "--multiarch" ]]
	then
		IAMROOT_MULTIARCH="1"
		export IAMROOT_MULTIARCH
	elif [[ "$1" == "--rc-file" ]]
	then
		shift
		ISH_RC_FILE="$1"
		export ISH_RC_FILE
	elif [[ "$1" == "--profile-file" ]]
	then
		shift
		ISH_PROFILE_FILE="$1"
		export ISH_PROFILE_FILE
	elif [[ "$1" == "--root" ]]
	then
		shift
		IAMROOT_ROOT="$1"
		export IAMROOT_ROOT
	elif [[ "$1" == "--" ]]
	then
		shift
		break
	else
		break
	fi
	shift
done

if [[ "$USER" == "root" ]] && [[ "$SUDO_USER" ]]
then
	exec "${SHELL:-/bin/sh}" "$@"
	exit 127
fi

if [[ "${IAMROOT_DEBUG_FD:-}" ]] && [[ ! -e "/proc/$$/fd/$IAMROOT_DEBUG_FD" ]]
then
	eval "exec $IAMROOT_DEBUG_FD>&2"
fi

for i in "${ISH_PROFILE_FILE:-}" "${ISH_RC_FILE:-}"
do
	if [[ ! "$i" ]]
	then
		continue
	fi

	cd "${i%/*}"
	PWD="$OLDPWD" source "${i##*/}"
	cd "$OLDPWD"
done

if [[ "$IAMROOT_ROOT" ]]
then
	cd "$IAMROOT_ROOT"

	IFS=: read -r -a __ <<<"${LD_LIBRARY_PATH:-/usr/lib:/lib}"
	LD_LIBRARY_PATH="$IAMROOT_ROOT${__[0]}"
	for i in "${__[@]:1}"
	do
		LD_LIBRARY_PATH+=":$IAMROOT_ROOT${__[0]}"
	done
fi

ISHLVL="$((ISHLVL+1))" \
PATH="${PATH:-/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin}" \
LD_PRELOAD="$IAMROOT_LIB${LD_PRELOAD+:$LD_PRELOAD}" \
LD_LIBRARY_PATH="$LD_LIBRARY_PATH" \
exec "${SHELL:-/bin/sh}" "$@"
