= ld-iamroot.so(8)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: ld-iamroot.so Manual
:man source: iamroot 21

== NAME

ld-iamroot.so - execute the program in an iamroot environment

== SYNOPSIS

_/usr/lib/iamroot/ld-iamroot.so_ [OPTIONS] [--] [PROGRAM [ARGUMENTS]]

== DESCRIPTION

Executes the _PROGRAM_ in an iamroot environment ready to emulate the
*chroot*(2) syscall for unprivileged users.

Under the hood, */usr/lib/iamroot/ld-iamroot.so* runs the _PROGRAM_ with its
_ARGUMENTS_ by rewriting the command-line using the dynamic loader stored in
the *.interp* section of the _PROGRAM_.

For a more thorough description of *ld.so*(8), *ld-linux.so*(8), or any other
dynamic loader, please refers to their manuals.

== OPTIONS

*-A* or *--argv0* _string_::
	Set argv[0] to the value _string_ before running the PROGRAM.

*-P* or *--preload* _list_::
	Preload the objects specified in _list_.

*-L* or *--library-path* _path_::
	Use _path_ instead of *LD_LIBRARY_PATH* environment variable setting.

*-M* or *--multiarch*::
	Use multiarch library path in chroot.

*-R* or *--root* _dir_::
	Set root directory to _dir_.

*-C* or *--cwd* _dir_::
	Set current working directory to _dir_.

*-D* or *--debug*::
	Turn on debug mode.

*-h* or *--help*::
	Display this message.

*-V* or *--version*::
	Display the version.

== ENVIRONMENT VARIABLES

**IAMROOT_MULTIARCH**::
	Use multiarch default library path in chroot.
	Equivalent to --multiarch.

*IAMROOT_ROOT*::
	Set absolute path to root directory to chroot in.
	Equivalent to --root DIR.

*LD_LIBRARY_PATH*::
	A list of directories in which to search for ELF libraries at execution
	time. The items in the list are separated by either colons or
	semicolons, and there is no support for escaping either separator. A
	zero-length directory name indicates the current working directory.

*LD_PRELOAD*::
	A list of additional, user-specified, ELF shared objects to be loaded
	before all others. This feature can be used to selectively override
	functions in other shared objects.

== BUGS

Report bugs at *https://github.com/gportay/iamroot/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright (c) 2024 Gaël PORTAY

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

*iamroot*(7), *ld.so*(8), *ld.so*(8), *ld-linux.so*(8), *chroot*(2)
