name: FreeBSD-vm
on: workflow_dispatch
jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
    - uses: actions/checkout@v3
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg install -y bash
          pkg install -y gmake
        run: |
          gmake test
