name: NetBSD-vm
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in NetBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        prepare: |
          /usr/sbin/pkg_add bash
          /usr/sbin/pkg_add gmake
        run: |
          gmake test
