name: OpenBSD-vm
on: workflow_dispatch
jobs:
  compile:
    runs-on: macos-12
    name: A job to run compile in OpenBSD
    steps:
    - uses: actions/checkout@v3
    - name: Compile in OpenBSD
      id: compile
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg_add bash
          pkg_add gmake
        run: |
          gmake
